include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Existing rules
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - require_trailing_commas

    # Code quality
    - avoid_empty_else
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - empty_catches
    - no_duplicate_case_values
    - throw_in_finally
    - unnecessary_statements

    # Style consistency
    - cascade_invocations
    - prefer_single_quotes
    - sort_child_properties_last
    - unnecessary_parenthesis
    - unnecessary_string_interpolations
    - use_full_hex_values_for_flutter_colors

    # Documentation
    - slash_for_doc_comments
